### ISSUE TITLE
ldm client times out connecting to upstream if you run it with docker-20

### ISSUE THREAD

**Issue by amarouane-ABDELHAK** [Unidata/ldm-docker#87]
running unidata/ldm-docker in docker-20 (specifically `docker-20.10.4-1.amzn2.x86_64`) breaks the connection to upstream (connection timeout). The same image works fine using docker-19  (`Docker version 19.03.13-ce`)

**Comment by mcenirm** [comment]
More background information for the context in which we discovered this issue...

This is on amazonlinux2 x86_64 (EC2 instances in the NASA Earthdata Cloud environment, for what it's worth). As far as we know, the only difference between `ldmping` success and timeout failure inside the container is the Docker version. In fact, on the same instance, using `yum downgrade docker` magically let `ldmping` succeed without any other changes.

**Comment by mcenirm** [comment]
After more testing, as far as I can tell, the problem is related to being able to bind to a privileged port (< 1024). I used strace to see what network syscalls ldmping made, and compared the results between running as root and as the ldm user (uid 500), as well as between docker 19.03 and docker 20.10.

* As root: `sudo docker exec ldm strace -ff -e network /home/ldm/bin/ldmping -x -vl- -h $UPSTREAM`
* As ldm: `sudo docker exec -u 500 ldm strace -ff -e network /home/ldm/bin/ldmping -x -vl- -h $UPSTREAM`

They all showed this pattern:
* `socket(AF_INET, SOCK_STREAM, IPPROTO_TCP)`
* `bind(3, {sa_family=AF_INET, sin_port=htons(NNN), sin_addr=inet_addr("0.0.0.0")}, 16)`, were `NNN` is a port number around 600 or 700
* `connect(3, {sa_family=AF_INET, sin_port=htons(388), sin_addr=inet_addr("WW.XX.YY.ZZ")}, 16)`, where `WW.XX.YY.ZZ` is the IP address for the upstream

If the bind call succeeds, then the connect call times out. If the bind call fails (`-1 EACCES (Permission denied)`), then the connect call succeeds.

| User | docker-19.03 | docker-20.10 |
| -- | -- | -- |
| root | ❌ | ❌ |
| ldm | ✔️ | ❌ |

Ultimately, I think this is related to the NAT implementation that we're required to use. I suspect it's filtering the return packets to the privileged ports. I've asked for confirmation, and I'll update this if I find out anything.

**Comment by julienchastang** [comment]
First, sorry for the delayed response. This issue got buried in my GitHub folder. Second, thank you for your thorough analysis. Pinging @semmerson and @tyoksas if they have ever seen anything like this before (independent of docker).

**Comment by semmerson** [comment]
We've seen connection timeouts when a reverse-DNS lookup of the incoming IP address by the LDM server doesn't work and the incoming IP address doesn't match an ALLOW entry in the LDM configuration-file.

It's more likely that a firewall is blocking return packets than a network address translation (NAT) device.

It would also appear that docker-20.10 has a problem.

**Comment by mcenirm** [comment]
As for docker 20.10, I think https://github.com/moby/moby/pull/41030 is the point where they enable `CAP_NET_BIND_SERVICE` by default.

As for the firewall, yes, definitely that is involved. Specifically, NASA is using AWS Virtual Private Cloud (VPC) Network Access Control List (NACL). The NACL implementation is stateless, and so the VPC administrator has to make sure that the return packets are explicitly allowed. Of course, for TCP connections, that's insane without going through a lot of excessive application configuration or just adding ALL return ports. Our particular situation involves a NACL that follows the advice given at https://aws.amazon.com/premiumsupport/knowledge-center/resolve-connection-sg-acl-inbound/ where they claim:

> When a client connects to a server, a random port from the ephemeral port range (1024-65535) becomes the client's source port.

Of course, that port range excludes the reserved ports (600-1023?) that the LDM is trying to use. I suspect the relevant parts of the code are:

* https://github.com/Unidata/LDM/blob/v6.13.7/rpc/bindresvport.c#L68 - The `bindresvport` function has constants that seem to define the range from 600 to 1023 and then later uses the process id to determine where in that range to start trying for ports that are not in use.
* https://github.com/Unidata/LDM/blob/v6.13.7/rpc/clnt_tcp.c#L407 - The `clnttcp_create` function calls `bindresvport` but ignores the results (whether success or failure).

In any case, we are looking at our options to manage the issue in our specific situation, but we don't have a good plan yet.

**Comment by semmerson** [comment]
So, a browser in the AWS VPC wouldn't be able to connect to an external web server using port 80? That is insane.

A downstream LDM will use an ephemeral port on its end to establish a TCP connection to port 388 on the upstream host. If the downstream LDM isn't doing that, then it's not my LDM.

The LDM doesn't call bindresvport().

**Comment by mcenirm** [comment]
The NACL allows outbound packets to ports 80 and 443, and that works as expected. If a client inside the VPC were to choose to bind the source endpoint to a reserved port, then the connections would fail to initialize, since the return packets (ie, SYN-ACK) would be blocked by the NACL. There's also a NAT proxy instance involved, so technically the EC2 instance running LDM on our side has a private address and the upstream node sees the NAT instance's public address. It's opaque to me, so I can simply trust that it's doing the NAT stuff correctly.

The specific LDM client being used is `ldmping` from the docker image produced by this GitHub repo. As described in the `strace` excerpt in the previous comment, it is definitely calling `bind` with a reserved port number before it calls `connect` to establish the connection. I have not tried using a normal debugger to determine the internal function calls involved.

We've been using `ldmping` to verify the upstream node likes us. Is there a better tool to use for that test? (eg, `notifyme`)

**Comment by semmerson** [comment]
Is the following correct? You're running an LDM in EC2 and it's timing-out trying to connect to an upstream LDM that's outside of AWS.. Meanwhile, a web browser in EC2 can connect to a web server that's outside AWS.

If this is the case, then you'll need to configure your firewall to allow your EC2 instance to initiate a TCP connection to port 388 on a host that's outside of AWS in the same manner that it allows such a connection to port 80.

You can use the `notifyme` utility to test/verify access to the upstream LDM on _host_ via the command
    `notifyme -vl- -h` _host_

**Comment by mcenirm** [comment]
Yes, that's all correct, and there's already an outbound allow rule to port 388 to our upstream nodes. The problem is when the LDM software (at least, ldmping) _successfully_ binds the source endpoint to a reserved port. In that situation, the NASA-managed firewall breaks the TCP connection handshake. (A quick test of notifyme under strace shows the same "attempt to bind a reserved port, but connect whether bind succeeds or fails" system call sequence.)

Our LDM setup is actually running inside a Docker container (in the EC2 instance), and has been working happily for months. When the Docker RPM package upgraded from 19.03 to 20.10 (which by default allows non-root users inside the container to bind reserved ports), then our ldmping test started failing. All the other components remained the same, and downgrading Docker to 19.03 avoided the problem.

Ultimately, I think we'll have to resolve our specific problem through some means other than changes to the LDM components. Having said that, I have a few questions about the behavior we're seeing:

* Are the LDM client utilities (eg, ldmping and notifyme, maybe others?) _supposed_ to try to bind a reserved port?
   * If so, then is that something that we can turn off using an existing configuration option?
* The LDM server (ie, ldmd) necessarily binds a reserved port (ie, 388) when it is listening for connections, but does it also try for connections to other nodes (eg, REQUESTs to upstreams)?
   * If not, then does that mean that the client utilities and ldmd use different protocol client functions? (perhaps related to setuid and dropping those privileges)

**Comment by semmerson** [comment]
The `ldmping(1)` and `notifyme(1)` utilities use the RPC standard function `clnttcp_create(3)` to create a connection to a remote LDM. Unfortunately, that function calls `bindresvport()`, which, as you've seen, causes problems. I've modified the `clnttcp_create(3)` function in the LDM package so that it now uses an ephemeral port number. This should obviate the problem.

Would you like a beta of the new version?

The LDM server, `ldmd(1)`, creates its own socket and doesn't use `clnttcp_create(3)` at all. So it can't have this problem.

> Are the LDM client utilities (eg, ldmping and notifyme, maybe others?) supposed to try to bind a reserved port?

IMO, no. That's why I've modified the RPC source.

Feel free to ask further questions.

**Comment by mcenirm** [comment]
Thanks for the confirmation.

I see that the https://github.com/Unidata/LDM/tree/devel branch has the change. Yes, we'd definitely like to test it, but I haven't had time or focus to be able to make a relevant test setup yet.

**Comment by semmerson** [comment]
Our Docker expert won't be available until next Tuesday. We'll see then.

**Comment by julienchastang** [comment]
It is more of a staycation style vacation. :-) I'm happy to pitch in where I can but the way I usually build this container is by grabbing:

```
wget https://www.unidata.ucar.edu/downloads/ldm/ldm-${LDM_VERSION}.tar.gz
```

Can we get something equivalent for the `devel` branch?

**Comment by semmerson** [comment]
>
> wget https://www.unidata.ucar.edu/downloads/ldm/ldm-${LDM_VERSION}.tar.gz
>
> Can we get something equivalent for the devel branch?
>

ftp://ftp.unidata.ucar.edu/pub/ldm/beta/6.13.14.28.tar.gz

--Steve

**Comment by julienchastang** [comment]
Thanks @semmerson. `ftp` is somewhat problematic these days (I tried a few things but could not get them to work). Can you put the `tar.gz` somewhere near https://www.unidata.ucar.edu/downloads/ldm/ accessible over https? Thank you.

**Comment by semmerson** [comment]
Hi Julien,

Try https://www.unidata.ucar.edu/downloads/ldm/beta/ldm-6.13.14.28.tar.gz

Regards,
Steve Emmerson

**Comment by julienchastang** [comment]
Thanks @semmerson. @amarouane-ABDELHAK @mcenirm Give it a shot:

```
docker pull unidata/ldm-docker:6.13.14.28
```

**Comment by amarouane-ABDELHAK** [comment]
Thank you, I tried it but got this error 
`mv: '/var/spool/cron/ldm' and '/var/spool/cron/ldm' are the same file` when trying to run it using docker-compose we didn't have this error in the previous version.
for reference I am using this docker-compose file https://github.com/ghrcdaac/ldm-ghrc-docker/blob/master/docker-compose.yml

**Comment by amarouane-ABDELHAK** [comment]
Running docker-compose using `unidata/ldm-docker:6.13.14.28`
`ldm    | mv: '/var/spool/cron/ldm' and '/var/spool/cron/ldm' are the same file
ldm    | groupadd: group 'ldm' already exists
ldm    | mv: '/var/spool/cron/ldm' and '/var/spool/cron/ldm' are the same file
ldm exited with code 1`

Running docker-compose using `unidata/ldm-docker:6.13.7`
`ldm    | Checking LDM configuration-file (/home/ldm/etc/ldmd.conf)...
ldm    | Starting the LDM server...
ldm    | + true
ldm    | + sleep 10000`

**Comment by julienchastang** [comment]
I don't really get these error messages. It is almost as if you are entering a container that is already running (e.g., `groupadd: group 'ldm' already exists`, how is that possible?). Can you ensure there are no running containers with `docker ps` before starting the ldm container?

**Comment by amarouane-ABDELHAK** [comment]
I don't have any container running
![image](https://user-images.githubusercontent.com/33136280/117044062-97cfff80-acd3-11eb-9b52-c3426d0c834b.png)

**Comment by amarouane-ABDELHAK** [comment]
![image](https://user-images.githubusercontent.com/33136280/117044974-9ce17e80-acd4-11eb-9f02-d5efd7666593.png)

**Comment by julienchastang** [comment]
My testing environment for this container is out of date. I will work on getting that going again and try to get back to you later in the week. I am perplexed. [As you can see, the change set](https://github.com/Unidata/ldm-docker/commit/f9f9d0076cfb278c714f5f2ca06647a0d99a1cdd) is really minimal so I don't know what is going on.

**Comment by amarouane-ABDELHAK** [comment]
The version I was using earlier doesn't have the `mv` command https://github.com/Unidata/ldm-docker/blob/6.13.7/entrypoint.sh#L29 compared the new one https://github.com/Unidata/ldm-docker/blob/fbf55cc2e0cf0103d6fe2e85b72815be5ec3a85b/entrypoint.sh#L40
Maybe that would help

**Comment by julienchastang** [comment]
ping @CameronLP for the`mv` problem. Thxs.

**Comment by julienchastang** [comment]
@amarouane-ABDELHAK `unidata/ldm-docker:6.13.14.28` is now branched off of `unidata/ldm-docker:6.13.13` instead of `master` while we get the other problems sorted out. Give it another shot.

**Comment by julienchastang** [comment]
FWIW, the `unidata/ldm-docker:6.13.14.28` seems to be working according to at least one of my tests. I am running on a Linux VM with:

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial
```

```
$ docker --version
Docker version 20.10.6, build 370c289
```

(Yeah, I think PR #86 appears to be problematic.)

**Comment by amarouane-ABDELHAK** [comment]
Yes, I could successfully ldmping the host using `Docker version 20.10.6, build 370c289`. Thank you for all your help

**Comment by julienchastang** [comment]
[Now that I have my test working again](https://github.com/Unidata/ldm-docker/tree/master/example) (also [documented here](https://github.com/Unidata/ldm-docker#self-contained-example) ), I just tested every LDM version I have available via Docker and they all worked, except `latest`:

- ✅ `unidata/ldm-docker:6.13.14.28`
- ✅ `unidata/ldm-docker:6.13.13`
- ✅ `unidata/ldm-docker:6.13.11`
- ✅ `unidata/ldm-docker:6.13.10`
- ✅ `unidata/ldm-docker:6.13.7`
- ✅ `unidata/ldm-docker:6.13.6`
- ❌ `unidata/ldm-docker:latest` (ping @CameronLP,  PR #86)

Again, I tested on:

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial

$ docker --version
Docker version 20.10.6, build 370c289
```

**Comment by semmerson** [comment]
@julienchastang, is this a Docker or LDM problem?

**Comment by julienchastang** [comment]
Thanks @semmerson. For this particular problem, it has nothing to do with the LDM :-)

**Comment by julienchastang** [comment]
Closing as this issue has been inactive.
